[workspace]
authors = ["Daniel San José Pro <42489409+danielsanjosepro@users.noreply.github.com>"]
name = "franka_ros2_pixi"
version = "0.1.0"
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["scripts/set_ros_env.sh", "install/setup.bash"]

[dependencies]
python = "*"
compilers = "*"
cmake = ">=3.26,<4"
pkg-config = "*"
make = "*"
ninja = "*"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
humble = { features = ["humble", "dev", "extra", "crisp"] }

# humble
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.7.0,<4"
poco = ">=1.14.2,<2"
ros-humble-ament-clang-format = "*"
ros-humble-desktop = "*"
ros-humble-joint-state-publisher = "*"
ros-humble-moveit-core = "*"
ros-humble-moveit-kinematics = "*"
ros-humble-moveit-planners-ompl = "*"
ros-humble-moveit-ros-move-group = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-ros2-control = "*"
ros-humble-ros2-control-cmake = "*"
ros-humble-ros2-controllers = "*"
ros-humble-xacro = "*"
rosdep = "*"

[feature.humble.tasks]
clone = "bash scripts/clone_sources.sh"
verify-sources = "bash scripts/verify_sources.sh"
update-libfranka = "cd src/libfranka && git submodule update --init --recursive && cd ../../"
apply-patches = "bash scripts/apply_patches.sh"
ignore-gazebo = "touch src/franka_ros2/franka_gazebo/COLCON_IGNORE"
build = "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DPython_ROOT_DIR=$CONDA_PREFIX -DPython3_ROOT_DIR=$CONDA_PREFIX -DPython_FIND_STRATEGY=LOCATION -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev"
setup = { depends-on = ["clone", "update-libfranka", "verify-sources", "apply-patches", "ignore-gazebo", "build"] }
franka = "ros2 launch scripts/launch/franka.launch.py"

[feature.crisp.tasks]
crisp-figure-eight = "python examples/crisp_figure_eight.py"
crisp-teleop = "python examples/crisp_teleop.py"

[feature.dev.pypi-dependencies]
ruff= "*"
bumpver = "*"
build = "*"
twine = "*"
pre-commit = "*"
pytest = "*"  # for testing

[feature.extra.pypi-dependencies]
rich = "*"  # For nice prints
matplotlib = "*"  # to do some plots

[feature.crisp.pypi-dependencies]
crisp-python = ">=3.0.0,<4"
